Add usage, change entire format and support multi os  Branch master  Your branch is up to date with 'origin/master'.
 コミット予定の変更点:
	deleted:    format_table.sh
	modified:   html_img_base64enc.sh
	modified:   open_browser.sh
	modified:   plantuml.sh
	modified:   sha256sumClip

diff --git a/sha256sumClip b/sha256sumClip
--- a/sha256sumClip
+++ b/sha256sumClip
@@ -1,3 +1,69 @@
-#!/bin/bash
+#! /bin/bash
 
-cat - | sha256sum | cut -c 1-64 | xsel -bi
+###############################################################################
+#
+# sha256sumClip - make it easier to copy the result of sha256sum to clipboard.
+#
+# USAGE       :  sha256sumClip text
+# ARGS        :  text
+#                  text you want to filter sha256sum.
+# 
+# 
+# 
+# Written by ppdx999 on 2020-08-14
+# 
+# 
+# This is a public-domain software (CC0). It means that all of the
+# people can use this for any purposes with no restrictions at all. 
+# 
+# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
+# IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
+# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
+# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
+# OTHER DEALINGS IN THE SOFTWARE.
+# 
+# For more information, please refer to <http://unlicense.org>
+# 
+###############################################################################
+
+error_exit() {
+	echo "$0: ${1:-"Unknown Error"}" 1>&2
+	exit 1
+}
+
+print_usage_and_exit() {
+  cat <<-USAGE 1>&2
+    USAGE       :  sha256sumClip text
+    ARGS        :  text
+                     text you want to filter sha256sum.
+	USAGE
+  exit 1
+}
+
+_main() {
+  case "$(uname -s)" in
+    Linux*)   
+      cat - | sha256sum | cut -c 1-64 | xsel -bi
+      ;;
+    Darwin*)   
+      cat - | sha256sum | cut -c 1-64 | pbcopy
+      ;;
+    CYGWIN* | MINGW*)   
+      cat - | sha256sum | cut -c 1-64 | clip 
+      ;;
+    *)         
+       error_exit "Unknown os:$(uname -s)"
+  esac
+}
+
+if [ -p /dev/stdin ]; then
+  cat - | _main
+else
+	[ $# -eq 0 ] && print_usage_and_exit
+  echo -n "$1" | _main 
+fi
+
+
+
